### ISSUE TITLE
ChebNet dataset

### ISSUE THREAD

**Issue by thomle295** [dsgiitr/graph_nets#16]
I saw the code has this code sentence
<img width="681" alt="image" src="https://user-images.githubusercontent.com/84239669/185735835-7fb13c8d-c682-4aaf-9bbc-de546dcbbfc1.png">
how can i get this datasets folder

**Comment by Garg-Doppler** [comment]
@thomle295 Kindly mention the file in which you saw this line.

**Comment by Garg-Doppler** [comment]
You can try to load the MNIST data by modifying the line to this:

`mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)`

**Comment by Garg-Doppler** [comment]
I am assigning this issue to you, if it works for you, make a pr to close this issue.
